Use PyPi distribution for neb-tasks (#161)
The reason for uploading neb-tasks to pypi is:

It is currently not possible to upload nebuchadnezzar (v9.2.0) on pypi
with a direct dependency.

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading nebuchadnezzar-9.2.0-py3-none-any.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103k/103k [00:01<00:00, 86.6kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: "neb-tasks @ git+https://github.com/openstax/neb-tasks.git@master#egg=neb-tasks ; extra == 'tasks'" for url: https://upload.pypi.org/legacy/
```